### ISSUE TITLE
Reflection issue.

### ISSUE THREAD

**Issue by thret** [cemulate/polyomino-solver#5]
Noticed that it doesn't solve some problems because the S pattern is not reflected.
![No Solution](https://user-images.githubusercontent.com/7938959/154823837-ca56456b-0517-47e8-b2cb-8e7420ea49b5.JPG)
![Polyomino 21 Feb](https://user-images.githubusercontent.com/7938959/154823839-74a37e7d-fdc1-46d7-81a3-5a50eaa92eac.jpg)
![Solved](https://user-images.githubusercontent.com/7938959/154823840-b4580a47-d3e9-4e78-a162-04626a5ad4a7.JPG)

**Comment by cemulate** [comment]
Thanks! All the systems are actually fully capable of allowing reflection as well as rotation, but the latter was turned off and that setting was not exposed anywhere in the UI. I've added checkboxes for rotation and reflection and verified that your example works (solves successfully when reflection is allowed via all three methods, and no solution otherwise).

Fixed by f2d680d

**Comment by thret** [comment]
Thank you Chase!

It's elegant and simple to use. A very clean design and neat code.

Perfection.

________________________________
